spring.application.name=intern managent


#mongodb connection
spring.mongodb.uri=mongodb://localhost:27017/internmanagementdb
spring.mongodb.database=internmanagementdb
spring.data.mongodb.auto-index-creation=true



